/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.trunk.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductField service. Represents a row in the &quot;Koroneiki_ProductField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.trunk.model.impl.ProductFieldModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.trunk.model.impl.ProductFieldImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductField
 * @generated
 */
@ProviderType
public interface ProductFieldModel
	extends AttachedModel, BaseModel<ProductField>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product field model instance should use the {@link ProductField} interface instead.
	 */

	/**
	 * Returns the primary key of this product field.
	 *
	 * @return the primary key of this product field
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product field.
	 *
	 * @param primaryKey the primary key of this product field
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product field ID of this product field.
	 *
	 * @return the product field ID of this product field
	 */
	public long getProductFieldId();

	/**
	 * Sets the product field ID of this product field.
	 *
	 * @param productFieldId the product field ID of this product field
	 */
	public void setProductFieldId(long productFieldId);

	/**
	 * Returns the company ID of this product field.
	 *
	 * @return the company ID of this product field
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product field.
	 *
	 * @param companyId the company ID of this product field
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product field.
	 *
	 * @return the user ID of this product field
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this product field.
	 *
	 * @param userId the user ID of this product field
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product field.
	 *
	 * @return the user uuid of this product field
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this product field.
	 *
	 * @param userUuid the user uuid of this product field
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the fully qualified class name of this product field.
	 *
	 * @return the fully qualified class name of this product field
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this product field.
	 *
	 * @return the class name ID of this product field
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this product field.
	 *
	 * @param classNameId the class name ID of this product field
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this product field.
	 *
	 * @return the class pk of this product field
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this product field.
	 *
	 * @param classPK the class pk of this product field
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the name of this product field.
	 *
	 * @return the name of this product field
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this product field.
	 *
	 * @param name the name of this product field
	 */
	public void setName(String name);

	/**
	 * Returns the value of this product field.
	 *
	 * @return the value of this product field
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this product field.
	 *
	 * @param value the value of this product field
	 */
	public void setValue(String value);

}