---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Eleflow Predictive Commerce"
host: "b2l9j0pz3i.execute-api.us-west-2.amazonaws.com"
basePath: "/Prod"
schemes:
- "https"
paths:
  /forecast:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "historySize"
        in: "query"
        required: false
        type: "string"
      - name: "date"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/Forecast"
      security:
      - api_key: []
  /orders:
    post:
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "OrderList"
        required: true
        schema:
          $ref: "#/definitions/OrderList"
      responses:
        200:
          description: "200 response"
      security:
      - api_key: []
  /scheduler:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ForecastScheduler"
      security:
      - api_key: []
    put:
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "ForecastScheduler"
        required: true
        schema:
          $ref: "#/definitions/ForecastScheduler"
      responses:
        200:
          description: "200 response"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Order:
    type: "object"
    required:
    - "companyId"
    - "createDate"
    - "items"
    - "orderId"
    properties:
      companyId:
        type: "string"
        description: "A company global unique identifier."
      orderId:
        type: "string"
        description: "Order unique identifier inside a store."
      customerId:
        type: "string"
        description: "User that placed the order. Id is unique in the company. Used\
          \ to do Product Recommendations."
      items:
        type: "array"
        description: "Items ordered"
        items:
          type: "object"
          properties:
            quantity:
              type: "number"
              description: "Amount of goods ordered. Used to Forecast Demand"
            price:
              type: "number"
              description: "Price of goods ordered. Used to Forecast Revenue."
            sku:
              type: "string"
              description: "SKU of the goods ordered. Used to Forecast and Recommend\
                \ Product."
          required:
          - "quantity"
          - "sku"
      createDate:
        type: "string"
        format: "date-time"
        description: "Date time the order was placed (ISO 8061)."
    description: "An E-Commerce Order"
  ForecastScheduler:
    type: "object"
    required:
    - "forecasts"
    - "frequency"
    - "timezone"
    properties:
      timezone:
        type: "string"
        description: "Forecast  process is  supposed to run in the first minutes of\
          \ the day in this timezone."
        pattern: "^(?:Z|[+-](?:2[0-3]|[01][0-9]):[0-5][0-9])$"
      callbackURL:
        type: "string"
        description: "URL to POST the date when the forecast is done. The receive\
          \ is supposed to call the GET /forecast with the date passed."
      forecasts:
        type: "array"
        description: "Forecast Specifications to be run."
        items:
          type: "object"
          properties:
            period:
              type: "string"
              enum:
              - "monthly"
              - "weekly"
            level:
              type: "string"
              description: "The level of the target has to be aggregated and forecasted"
              enum:
              - "company"
              - "customer"
              - "sku"
              - "customer-sku"
            ahead:
              type: "number"
              description: "Forecast n periods ahead."
            ids:
              type: "array"
              description: "Level ids to be included in the forecast. Abssence of\
                \ this proprety means all elegible."
              items:
                type: "string"
            target:
              type: "string"
              description: "The target to be forecasted"
              enum:
              - "revenue"
              - "quantity"
          required:
          - "ahead"
          - "level"
          - "period"
          - "target"
      frequency:
        type: "string"
        description: "The frequency that the scheduler has to run."
        enum:
        - "daily"
        - "weekly"
        - "monthly"
        default: "monthly"
  Forecast:
    type: "object"
    required:
    - "date"
    - "forecasts"
    - "scheduler"
    properties:
      date:
        type: "string"
        format: "date"
        description: "Reference date for the forecast."
      scheduler:
        description: "Process parameters that created this forecast."
        $ref: "#/definitions/ForecastScheduler"
      forecasts:
        type: "array"
        items:
          type: "object"
          properties:
            companyId:
              type: "string"
            period:
              type: "string"
              enum:
              - "monthly"
              - "weekly"
            timeseries:
              type: "array"
              items:
                type: "object"
                properties:
                  date:
                    type: "string"
                    format: "date"
                    description: "Future date of the forecast point."
                  upper:
                    type: "number"
                    description: "lower and upper form a boundary which the actual\
                      \ value has a 95% chance of being within it."
                  lower:
                    type: "number"
                    description: "lower and upper form a boundary which the actual\
                      \ value has a 95% chance of being within it."
                  value:
                    type: "number"
                    description: "forecasted value"
                required:
                - "date"
                - "value"
            level:
              type: "string"
              enum:
              - "company"
              - "customer"
              - "sku"
              - "customer-sku"
            customerId:
              type: "string"
            assertivity:
              type: "number"
            sku:
              type: "string"
            target:
              type: "string"
              enum:
              - "revenue"
              - "quantity"
          required:
          - "assertivity"
          - "period"
          - "target"
  OrderList:
    type: "array"
    description: "A list E-Commerce Orders"
    items:
      $ref: "#/definitions/Order"
