/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.taproot.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ContactRole service. Represents a row in the &quot;Koroneiki_ContactRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.taproot.model.impl.ContactRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.taproot.model.impl.ContactRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactRole
 * @generated
 */
@ProviderType
public interface ContactRoleModel
	extends BaseModel<ContactRole>, ShardedModel, StagedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact role model instance should use the {@link ContactRole} interface instead.
	 */

	/**
	 * Returns the primary key of this contact role.
	 *
	 * @return the primary key of this contact role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact role.
	 *
	 * @param primaryKey the primary key of this contact role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this contact role.
	 *
	 * @return the uuid of this contact role
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this contact role.
	 *
	 * @param uuid the uuid of this contact role
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the contact role ID of this contact role.
	 *
	 * @return the contact role ID of this contact role
	 */
	public long getContactRoleId();

	/**
	 * Sets the contact role ID of this contact role.
	 *
	 * @param contactRoleId the contact role ID of this contact role
	 */
	public void setContactRoleId(long contactRoleId);

	/**
	 * Returns the company ID of this contact role.
	 *
	 * @return the company ID of this contact role
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this contact role.
	 *
	 * @param companyId the company ID of this contact role
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contact role.
	 *
	 * @return the user ID of this contact role
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this contact role.
	 *
	 * @param userId the user ID of this contact role
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contact role.
	 *
	 * @return the user uuid of this contact role
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this contact role.
	 *
	 * @param userUuid the user uuid of this contact role
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this contact role.
	 *
	 * @return the create date of this contact role
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this contact role.
	 *
	 * @param createDate the create date of this contact role
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contact role.
	 *
	 * @return the modified date of this contact role
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contact role.
	 *
	 * @param modifiedDate the modified date of this contact role
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the contact role key of this contact role.
	 *
	 * @return the contact role key of this contact role
	 */
	@AutoEscape
	public String getContactRoleKey();

	/**
	 * Sets the contact role key of this contact role.
	 *
	 * @param contactRoleKey the contact role key of this contact role
	 */
	public void setContactRoleKey(String contactRoleKey);

	/**
	 * Returns the name of this contact role.
	 *
	 * @return the name of this contact role
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this contact role.
	 *
	 * @param name the name of this contact role
	 */
	public void setName(String name);

	/**
	 * Returns the description of this contact role.
	 *
	 * @return the description of this contact role
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this contact role.
	 *
	 * @param description the description of this contact role
	 */
	public void setDescription(String description);

	/**
	 * Returns the type of this contact role.
	 *
	 * @return the type of this contact role
	 */
	public int getType();

	/**
	 * Sets the type of this contact role.
	 *
	 * @param type the type of this contact role
	 */
	public void setType(int type);

	/**
	 * Returns the system of this contact role.
	 *
	 * @return the system of this contact role
	 */
	public boolean getSystem();

	/**
	 * Returns <code>true</code> if this contact role is system.
	 *
	 * @return <code>true</code> if this contact role is system; <code>false</code> otherwise
	 */
	public boolean isSystem();

	/**
	 * Sets whether this contact role is system.
	 *
	 * @param system the system of this contact role
	 */
	public void setSystem(boolean system);

}