/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.taproot.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TeamRole service. Represents a row in the &quot;Koroneiki_TeamRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.taproot.model.impl.TeamRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.taproot.model.impl.TeamRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeamRole
 * @generated
 */
@ProviderType
public interface TeamRoleModel
	extends BaseModel<TeamRole>, ShardedModel, StagedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a team role model instance should use the {@link TeamRole} interface instead.
	 */

	/**
	 * Returns the primary key of this team role.
	 *
	 * @return the primary key of this team role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this team role.
	 *
	 * @param primaryKey the primary key of this team role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this team role.
	 *
	 * @return the uuid of this team role
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this team role.
	 *
	 * @param uuid the uuid of this team role
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the team role ID of this team role.
	 *
	 * @return the team role ID of this team role
	 */
	public long getTeamRoleId();

	/**
	 * Sets the team role ID of this team role.
	 *
	 * @param teamRoleId the team role ID of this team role
	 */
	public void setTeamRoleId(long teamRoleId);

	/**
	 * Returns the company ID of this team role.
	 *
	 * @return the company ID of this team role
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this team role.
	 *
	 * @param companyId the company ID of this team role
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this team role.
	 *
	 * @return the user ID of this team role
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this team role.
	 *
	 * @param userId the user ID of this team role
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this team role.
	 *
	 * @return the user uuid of this team role
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this team role.
	 *
	 * @param userUuid the user uuid of this team role
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this team role.
	 *
	 * @return the create date of this team role
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this team role.
	 *
	 * @param createDate the create date of this team role
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this team role.
	 *
	 * @return the modified date of this team role
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this team role.
	 *
	 * @param modifiedDate the modified date of this team role
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the team role key of this team role.
	 *
	 * @return the team role key of this team role
	 */
	@AutoEscape
	public String getTeamRoleKey();

	/**
	 * Sets the team role key of this team role.
	 *
	 * @param teamRoleKey the team role key of this team role
	 */
	public void setTeamRoleKey(String teamRoleKey);

	/**
	 * Returns the name of this team role.
	 *
	 * @return the name of this team role
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this team role.
	 *
	 * @param name the name of this team role
	 */
	public void setName(String name);

	/**
	 * Returns the description of this team role.
	 *
	 * @return the description of this team role
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this team role.
	 *
	 * @param description the description of this team role
	 */
	public void setDescription(String description);

	/**
	 * Returns the type of this team role.
	 *
	 * @return the type of this team role
	 */
	public int getType();

	/**
	 * Sets the type of this team role.
	 *
	 * @param type the type of this team role
	 */
	public void setType(int type);

}