/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.taproot.model;

import com.liferay.osb.koroneiki.taproot.service.persistence.TeamAccountRolePK;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TeamAccountRole service. Represents a row in the &quot;Koroneiki_TeamAccountRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.taproot.model.impl.TeamAccountRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.taproot.model.impl.TeamAccountRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeamAccountRole
 * @generated
 */
@ProviderType
public interface TeamAccountRoleModel extends BaseModel<TeamAccountRole> {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a team account role model instance should use the {@link TeamAccountRole} interface instead.
	 */

	/**
	 * Returns the primary key of this team account role.
	 *
	 * @return the primary key of this team account role
	 */
	public TeamAccountRolePK getPrimaryKey();

	/**
	 * Sets the primary key of this team account role.
	 *
	 * @param primaryKey the primary key of this team account role
	 */
	public void setPrimaryKey(TeamAccountRolePK primaryKey);

	/**
	 * Returns the team ID of this team account role.
	 *
	 * @return the team ID of this team account role
	 */
	public long getTeamId();

	/**
	 * Sets the team ID of this team account role.
	 *
	 * @param teamId the team ID of this team account role
	 */
	public void setTeamId(long teamId);

	/**
	 * Returns the account ID of this team account role.
	 *
	 * @return the account ID of this team account role
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this team account role.
	 *
	 * @param accountId the account ID of this team account role
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the team role ID of this team account role.
	 *
	 * @return the team role ID of this team account role
	 */
	public long getTeamRoleId();

	/**
	 * Sets the team role ID of this team account role.
	 *
	 * @param teamRoleId the team role ID of this team account role
	 */
	public void setTeamRoleId(long teamRoleId);

}