/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.scion.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ServiceProducer service. Represents a row in the &quot;Koroneiki_ServiceProducer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.scion.model.impl.ServiceProducerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.scion.model.impl.ServiceProducerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServiceProducer
 * @generated
 */
@ProviderType
public interface ServiceProducerModel
	extends BaseModel<ServiceProducer>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service producer model instance should use the {@link ServiceProducer} interface instead.
	 */

	/**
	 * Returns the primary key of this service producer.
	 *
	 * @return the primary key of this service producer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service producer.
	 *
	 * @param primaryKey the primary key of this service producer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this service producer.
	 *
	 * @return the uuid of this service producer
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this service producer.
	 *
	 * @param uuid the uuid of this service producer
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the service producer ID of this service producer.
	 *
	 * @return the service producer ID of this service producer
	 */
	public long getServiceProducerId();

	/**
	 * Sets the service producer ID of this service producer.
	 *
	 * @param serviceProducerId the service producer ID of this service producer
	 */
	public void setServiceProducerId(long serviceProducerId);

	/**
	 * Returns the company ID of this service producer.
	 *
	 * @return the company ID of this service producer
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this service producer.
	 *
	 * @param companyId the company ID of this service producer
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this service producer.
	 *
	 * @return the user ID of this service producer
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this service producer.
	 *
	 * @param userId the user ID of this service producer
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this service producer.
	 *
	 * @return the user uuid of this service producer
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this service producer.
	 *
	 * @param userUuid the user uuid of this service producer
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the authorization user ID of this service producer.
	 *
	 * @return the authorization user ID of this service producer
	 */
	public long getAuthorizationUserId();

	/**
	 * Sets the authorization user ID of this service producer.
	 *
	 * @param authorizationUserId the authorization user ID of this service producer
	 */
	public void setAuthorizationUserId(long authorizationUserId);

	/**
	 * Returns the authorization user uuid of this service producer.
	 *
	 * @return the authorization user uuid of this service producer
	 */
	public String getAuthorizationUserUuid();

	/**
	 * Sets the authorization user uuid of this service producer.
	 *
	 * @param authorizationUserUuid the authorization user uuid of this service producer
	 */
	public void setAuthorizationUserUuid(String authorizationUserUuid);

	/**
	 * Returns the name of this service producer.
	 *
	 * @return the name of this service producer
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this service producer.
	 *
	 * @param name the name of this service producer
	 */
	public void setName(String name);

	/**
	 * Returns the description of this service producer.
	 *
	 * @return the description of this service producer
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this service producer.
	 *
	 * @param description the description of this service producer
	 */
	public void setDescription(String description);

}