apiDir: "../portal-workflow-metrics-rest-api/src/main/java"
apiPackagePath: "com.liferay.portal.workflow.metrics.rest"
application:
    baseURI: "/portal-workflow-metrics-rest"
    className: "PortalWorkflowMetricsRestApplication"
    name: "portal-workflow-metrics-rest-application"
author: "Rafael Praxedes"