components:
  schemas:
    Process:
      description: https://www.schema.org/Process
      properties:
        id:
          format: int64
          type: integer
        instanceCount:
          type: integer
        ontimeInstanceCount:
          type: integer
        overdueInstanceCount:
          type: integer
        title:
          type: string
      type: object
info:
  description: ""
  title: ""
  version: v1.0
openapi: 3.0.1
paths:
  "/process":
    get:
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
        - in: query
          name: title
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Process"
                type: array
          description: ""