components:
    schemas:
        GenericError:
            description: https://www.schema.org/GenericError
            properties:
                fieldName:
                    type: string
                message:
                    type: string
            type: object
        Instance:
            description: https://www.schema.org/Instance
            properties:
                assetTitle:
                    type: string
                assetType:
                    type: string
                dateCreated:
                    format: date-time
                    type: string
                id:
                    format: int64
                    type: integer
                status:
                    enum: [OnTime, Overdue, Untracked]
                    type: string
                taskNames:
                    items:
                        type: string
                    type: array
                userName:
                    type: string
            type: object
        Node:
            description: https://www.schema.org/Node
            properties:
                id:
                    format: int64
                    type: integer
                initial:
                    type: boolean
                name:
                    type: string
                terminal:
                    type: boolean
                type:
                    type: string
            type: object
        Process:
            description: https://www.schema.org/Process
            properties:
                id:
                    format: int64
                    type: integer
                instanceCount:
                    format: int64
                    type: integer
                onTimeInstanceCount:
                    format: int64
                    type: integer
                overdueInstanceCount:
                    format: int64
                    type: integer
                title:
                    type: string
                untrackedInstanceCount:
                    format: int64
                    type: integer
            type: object
        SLA:
            description: https://www.schema.org/SLA
            properties:
                dateModified:
                    format: date-time
                    type: string
                description:
                    type: string
                duration:
                    format: int64
                    type: integer
                id:
                    format: int64
                    type: integer
                name:
                    type: string
                pauseNodeKeys:
                    items:
                        type: string
                    type: array
                processId:
                    format: int64
                    type: integer
                startNodeKeys:
                    items:
                        type: string
                    type: array
                status:
                    type: integer
                stopNodeKeys:
                    items:
                        type: string
                    type: array
            type: object
        Task:
            description: https://www.schema.org/Task
            properties:
                instanceCount:
                    format: int64
                    type: integer
                name:
                    type: string
                onTimeInstanceCount:
                    format: int64
                    type: integer
                overdueInstanceCount:
                    format: int64
                    type: integer
            type: object
info:
    description: ""
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/processes":
        get:
            operationId: getProcessesPage
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: sort
                  schema:
                      type: string
                - in: query
                  name: title
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Process"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Process"
                                type: array
                    description: ""
            tags: ["Process"]
    "/processes/{processId}":
        get:
            operationId: getProcess
            parameters:
                - in: path
                  name: processId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: completed
                  required: true
                  schema:
                      type: boolean
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Process"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Process"
                    description: ""
            tags: ["Process"]
    "/processes/{processId}/instances":
        get:
            operationId: getProcessInstancesPage
            parameters:
                - in: path
                  name: processId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Instance"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Instance"
                                type: array
                    description: ""
            tags: ["Instance"]
    "/processes/{processId}/nodes":
        get:
            operationId: getProcessNodesPage
            parameters:
                - in: path
                  name: processId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Node"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Node"
                                type: array
                    description: ""
            tags: ["Node"]
    "/processes/{processId}/slas":
        get:
            operationId: getProcessSLAsPage
            parameters:
                - in: path
                  name: processId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: status
                  required: false
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SLA"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/SLA"
                                type: array
                    description: ""
            tags: ["SLA"]
        post:
            operationId: postProcessSLA
            parameters:
                - in: path
                  name: processId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SLA"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SLA"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SLA"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SLA"
                    description: ""
                400:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GenericError"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/GenericError"
                    description: ""
            tags: ["SLA"]
    "/processes/{processId}/tasks":
        get:
            operationId: getProcessTasksPage
            parameters:
                - in: path
                  name: processId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Task"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Task"
                                type: array
                    description: ""
            tags: ["Task"]
    "/processes/{processId}/title":
        get:
            operationId: getProcessTitle
            parameters:
                - in: path
                  name: processId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        text/plain:
                            schema:
                                type: string
                    description: ""
            tags: ["Process"]
    "/slas/{slaId}":
        delete:
            operationId: deleteSLA
            parameters:
                - in: path
                  name: slaId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                    description: ""
            tags: ["SLA"]
        get:
            operationId: getSLA
            parameters:
                - in: path
                  name: slaId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SLA"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SLA"
                    description: ""
            tags: ["SLA"]
        put:
            operationId: putSLA
            parameters:
                - in: path
                  name: slaId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SLA"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SLA"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SLA"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SLA"
                    description: ""
                400:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GenericError"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/GenericError"
                    description: ""
            tags: ["SLA"]